services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jira_development
    ports:
      - 5432:5432
    networks:
      - shared-network
    volumes:
      - ./postgres-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - shared-network
    depends_on:
      - postgres

  api:
    container_name: jira_api
    restart: unless-stopped
    image: jira-api-prod:1.0.0
    build:
      context: api
      target: development
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=jira_development
      - JWT_SECRET=development12345
    ports:
      - 3000:3000
    networks:
      - shared-network
    depends_on:
      - postgres

  client:
    container_name: jira_client
    restart: unless-stopped
    image: jira-client-prod:1.0.0
    build:
      context: client
      target: development
      dockerfile: Dockerfile
    ports:
      - 8080:8081
    networks:
      - shared-network
    depends_on:
      - api

networks:
  shared-network:
    driver: bridge
